'use server'
import { Box, Grid, VStack, Text, HStack, Avatar, Icon, Link } from '@chakra-ui/react';
import { FaGithub, FaLinkedin, FaYoutube, FaEnvelope } from 'react-icons/fa';
import { Inter } from "next/font/google";
import "../globals.css";

const AdminLayout = ({ children }) => {
    // Example logged-in admin user
    const adminUser = {
        name: 'Admin User',
        avatar: '/avatar.png'
    };

    // const inter = Inter({ subsets: ["latin"] });

    const metadata = {
        title: "User Dashboard",
        description: "Generated by kaw393939",
    };

    return (
        <Grid templateColumns={['1fr', '220px 1fr']} gap={4} minHeight="100vh">
            {/* Sidebar */}
            <Box bg="lightblue" p={4} display={['none', 'block']} minHeight="100vh">
                <VStack spacing={4}>
                    <Avatar name={adminUser.name} src={adminUser.avatar} />
                    <Text>Welcome, {adminUser.name}!</Text>
                </VStack>
            </Box>

            {/* Main Content */}
            <Box p={6} flex="1">
                {children}
                {/* Footer Section */}
                <Box mt={10} pt={6} borderTop="1px solid" borderColor="gray.200">
                    <HStack justifyContent="center" mb={2} spacing={4}>
                        {/* <Link href="https://github.com" isExternal><Icon as={FaGithub} /></Link>
                        <Link href="https://linkedin.com" isExternal><Icon as={FaLinkedin} /></Link>
                        <Link href="https://youtube.com" isExternal><Icon as={FaYoutube} /></Link>
    <Link href="mailto:info@example.com"><Icon as={FaEnvelope} /></Link>*/}
                    </HStack>
                    <Text textAlign="center">© 2024 WIS Club</Text>
                </Box>
            </Box>
        </Grid>
    );
};

export default AdminLayout;
